# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/export/export.srcs/sources_1/ip/fir_TOP_0/fir_TOP_0.xci
# IP: The module: 'fir_TOP_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/export/export.gen/sources_1/ip/fir_TOP_0/constraints/fir_TOP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_TOP_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/export/export.srcs/sources_1/ip/fir_TOP_0/fir_TOP_0.xci
# IP: The module: 'fir_TOP_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/export/export.gen/sources_1/ip/fir_TOP_0/constraints/fir_TOP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_TOP_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
