// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lenet_predict_conv2d_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        filters,
        grp_fu_423_p_din0,
        grp_fu_423_p_din1,
        grp_fu_423_p_opcode,
        grp_fu_423_p_dout0,
        grp_fu_423_p_ce,
        grp_fu_909_p_din0,
        grp_fu_909_p_din1,
        grp_fu_909_p_opcode,
        grp_fu_909_p_dout0,
        grp_fu_909_p_ce,
        grp_fu_913_p_din0,
        grp_fu_913_p_din1,
        grp_fu_913_p_dout0,
        grp_fu_913_p_ce
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [10:0] input_r_address1;
output   input_r_ce1;
input  [31:0] input_r_q1;
output  [10:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] filters;
output  [31:0] grp_fu_423_p_din0;
output  [31:0] grp_fu_423_p_din1;
output  [4:0] grp_fu_423_p_opcode;
input  [0:0] grp_fu_423_p_dout0;
output   grp_fu_423_p_ce;
output  [31:0] grp_fu_909_p_din0;
output  [31:0] grp_fu_909_p_din1;
output  [0:0] grp_fu_909_p_opcode;
input  [31:0] grp_fu_909_p_dout0;
output   grp_fu_909_p_ce;
output  [31:0] grp_fu_913_p_din0;
output  [31:0] grp_fu_913_p_din1;
input  [31:0] grp_fu_913_p_dout0;
output   grp_fu_913_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[10:0] input_r_address0;
reg input_r_ce0;
reg[10:0] input_r_address1;
reg input_r_ce1;
reg[10:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;
reg m_axi_gmem_ARVALID;
reg[63:0] m_axi_gmem_ARADDR;
reg[0:0] m_axi_gmem_ARID;
reg[31:0] m_axi_gmem_ARLEN;
reg[2:0] m_axi_gmem_ARSIZE;
reg[1:0] m_axi_gmem_ARBURST;
reg[1:0] m_axi_gmem_ARLOCK;
reg[3:0] m_axi_gmem_ARCACHE;
reg[2:0] m_axi_gmem_ARPROT;
reg[3:0] m_axi_gmem_ARQOS;
reg[3:0] m_axi_gmem_ARREGION;
reg[0:0] m_axi_gmem_ARUSER;
reg m_axi_gmem_RREADY;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] p_cast9_mid2_fu_338_p2;
reg   [8:0] p_cast9_mid2_reg_724;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln32_fu_276_p2;
wire   [8:0] p_mid216_fu_359_p2;
reg   [8:0] p_mid216_reg_730;
wire   [3:0] select_ln33_fu_392_p3;
reg   [3:0] select_ln33_reg_736;
wire   [10:0] select_ln33_1_fu_437_p3;
reg   [10:0] select_ln33_1_reg_743;
wire   [3:0] select_ln33_2_fu_445_p3;
reg   [3:0] select_ln33_2_reg_749;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_return;
reg   [0:0] targetBlock_reg_755;
wire    ap_CS_fsm_state3;
wire   [31:0] select_ln38_fu_505_p3;
reg   [31:0] select_ln38_reg_760;
wire    ap_CS_fsm_state4;
wire   [3:0] or_ln34_fu_513_p2;
reg   [3:0] or_ln34_reg_767;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_return;
reg   [0:0] targetBlock1_reg_773;
wire    ap_CS_fsm_state5;
wire   [10:0] add_ln47_1_fu_584_p2;
reg   [10:0] add_ln47_1_reg_778;
wire   [31:0] select_ln38_1_fu_595_p3;
reg   [31:0] select_ln38_1_reg_783;
wire    ap_CS_fsm_state6;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_done;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_idle;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_ready;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWVALID;
wire   [63:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWADDR;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWID;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWLEN;
wire   [2:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWSIZE;
wire   [1:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWBURST;
wire   [1:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWLOCK;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWCACHE;
wire   [2:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWPROT;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWQOS;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWREGION;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWUSER;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WVALID;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WDATA;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WSTRB;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WLAST;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WID;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WUSER;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARVALID;
wire   [63:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARADDR;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARID;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARLEN;
wire   [2:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARSIZE;
wire   [1:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARBURST;
wire   [1:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARLOCK;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARCACHE;
wire   [2:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARPROT;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARQOS;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARREGION;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARUSER;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_RREADY;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_BREADY;
wire   [10:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_address0;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_ce0;
wire   [10:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_address1;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_ce1;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_out;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_out_ap_vld;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_16_4_out;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_16_4_out_ap_vld;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_din0;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_din1;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_opcode;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_ce;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_din0;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_din1;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_ce;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_done;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_idle;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_ready;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWVALID;
wire   [63:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWADDR;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWID;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWLEN;
wire   [2:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWSIZE;
wire   [1:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWBURST;
wire   [1:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWLOCK;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWCACHE;
wire   [2:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWPROT;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWQOS;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWREGION;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWUSER;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WVALID;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WDATA;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WSTRB;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WLAST;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WID;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WUSER;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARVALID;
wire   [63:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARADDR;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARID;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARLEN;
wire   [2:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARSIZE;
wire   [1:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARBURST;
wire   [1:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARLOCK;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARCACHE;
wire   [2:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARPROT;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARQOS;
wire   [3:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARREGION;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARUSER;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_RREADY;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_BREADY;
wire   [10:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_address0;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_ce0;
wire   [10:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_address1;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_ce1;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_11_out;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_11_out_ap_vld;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_23_4_out;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_23_4_out_ap_vld;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_din0;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_din1;
wire   [0:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_opcode;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_ce;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_din0;
wire   [31:0] grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_din1;
wire    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_ce;
reg    grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start_reg;
reg   [31:0] sum_loc_fu_130;
reg   [31:0] sum_16_4_loc_fu_126;
reg    grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start_reg;
reg   [31:0] sum_11_loc_fu_122;
reg   [31:0] sum_23_4_loc_fu_118;
wire   [63:0] zext_ln47_fu_576_p1;
wire   [63:0] zext_ln47_1_fu_652_p1;
wire    ap_CS_fsm_state7;
reg   [3:0] j_fu_98;
wire   [3:0] add_ln34_fu_454_p2;
reg   [3:0] i_fu_102;
reg   [6:0] indvar_flatten_fu_106;
wire   [6:0] select_ln33_3_fu_466_p3;
reg   [4:0] f_fu_110;
wire   [4:0] p_cast9_mid2_v_v_fu_326_p3;
reg   [9:0] indvar_flatten35_fu_114;
wire   [9:0] add_ln32_fu_282_p2;
wire   [31:0] select_ln7_fu_563_p3;
wire   [31:0] select_ln7_3_fu_644_p3;
reg   [31:0] grp_fu_191_p0;
wire   [4:0] empty_fu_234_p0;
wire   [7:0] empty_fu_234_p1;
wire   [6:0] p_shl_fu_240_p3;
wire   [4:0] p_shl1_fu_252_p3;
wire   [10:0] p_shl1_cast_fu_260_p1;
wire   [10:0] empty_fu_234_p2;
wire   [10:0] tmp_fu_264_p2;
wire   [10:0] p_shl_cast_fu_248_p1;
wire   [0:0] icmp_ln33_fu_294_p2;
wire   [4:0] add_ln32_1_fu_316_p2;
wire   [4:0] p_cast9_mid2_fu_338_p0;
wire   [5:0] p_cast9_mid2_fu_338_p1;
wire   [4:0] p_mid113_fu_345_p0;
wire   [7:0] p_mid113_fu_345_p1;
wire   [10:0] p_mid113_fu_345_p2;
wire   [10:0] empty_70_fu_270_p2;
wire   [0:0] icmp_ln34_fu_374_p2;
wire   [3:0] i_mid29_fu_300_p3;
wire   [0:0] icmp_ln34_mid234_fu_380_p2;
wire   [3:0] j_mid210_fu_308_p3;
wire   [3:0] add_ln33_fu_386_p2;
wire   [6:0] p_shl_mid1_fu_401_p3;
wire   [4:0] p_shl1_mid1_fu_413_p3;
wire   [10:0] p_shl1_cast_mid1_fu_421_p1;
wire   [10:0] p_mid214_fu_351_p3;
wire   [10:0] tmp_mid1_fu_425_p2;
wire   [10:0] p_shl_cast_mid1_fu_409_p1;
wire   [10:0] p_mid232_fu_366_p3;
wire   [10:0] p_mid1_fu_431_p2;
wire   [6:0] add_ln33_1_fu_460_p2;
wire   [31:0] bitcast_ln7_fu_522_p1;
wire   [7:0] tmp_s_fu_525_p4;
wire   [22:0] trunc_ln7_fu_535_p1;
wire   [0:0] icmp_ln7_6_fu_545_p2;
wire   [0:0] icmp_ln7_fu_539_p2;
wire   [0:0] or_ln7_fu_551_p2;
wire   [0:0] and_ln7_fu_557_p2;
wire   [10:0] zext_ln34_fu_519_p1;
wire   [10:0] add_ln47_fu_571_p2;
wire   [10:0] zext_ln38_fu_581_p1;
wire   [31:0] bitcast_ln7_3_fu_603_p1;
wire   [7:0] tmp_12_fu_606_p4;
wire   [22:0] trunc_ln7_3_fu_616_p1;
wire   [0:0] icmp_ln7_8_fu_626_p2;
wire   [0:0] icmp_ln7_7_fu_620_p2;
wire   [0:0] or_ln7_3_fu_632_p2;
wire   [0:0] and_ln7_3_fu_638_p2;
reg    grp_fu_191_ce;
reg   [31:0] grp_fu_790_p0;
reg   [31:0] grp_fu_790_p1;
reg   [1:0] grp_fu_790_opcode;
reg    grp_fu_790_ce;
reg   [31:0] grp_fu_794_p0;
reg   [31:0] grp_fu_794_p1;
reg    grp_fu_794_ce;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire   [10:0] empty_fu_234_p00;
wire   [8:0] p_cast9_mid2_fu_338_p00;
wire   [10:0] p_mid113_fu_345_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start_reg = 1'b0;
#0 grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start_reg = 1'b0;
end

lenet_predict_conv2d_1_Pipeline_VITIS_LOOP_38_4 grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start),
    .ap_done(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_done),
    .ap_idle(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_idle),
    .ap_ready(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_ready),
    .select_ln33_2(select_ln33_2_reg_749),
    .m_axi_gmem_AWVALID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RFIFONUM(m_axi_gmem_RFIFONUM),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .zext_ln34_1(select_ln33_reg_736),
    .input_r_address0(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_address0),
    .input_r_ce0(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_ce0),
    .input_r_q0(input_r_q0),
    .input_r_address1(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_address1),
    .input_r_ce1(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_ce1),
    .input_r_q1(input_r_q1),
    .p_cast9_mid2(p_cast9_mid2_reg_724),
    .filters(filters),
    .p_mid216(p_mid216_reg_730),
    .sum_out(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_out),
    .sum_out_ap_vld(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_out_ap_vld),
    .sum_16_4_out(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_16_4_out),
    .sum_16_4_out_ap_vld(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_16_4_out_ap_vld),
    .ap_return(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_return),
    .grp_fu_790_p_din0(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_din0),
    .grp_fu_790_p_din1(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_din1),
    .grp_fu_790_p_opcode(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_opcode),
    .grp_fu_790_p_dout0(grp_fu_909_p_dout0),
    .grp_fu_790_p_ce(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_ce),
    .grp_fu_794_p_din0(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_din0),
    .grp_fu_794_p_din1(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_din1),
    .grp_fu_794_p_dout0(grp_fu_913_p_dout0),
    .grp_fu_794_p_ce(grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_ce)
);

lenet_predict_conv2d_1_Pipeline_VITIS_LOOP_38_44 grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start),
    .ap_done(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_done),
    .ap_idle(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_idle),
    .ap_ready(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_ready),
    .select_ln33_2(select_ln33_2_reg_749),
    .m_axi_gmem_AWVALID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RFIFONUM(m_axi_gmem_RFIFONUM),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .zext_ln38_2(or_ln34_reg_767),
    .input_r_address0(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_address0),
    .input_r_ce0(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_ce0),
    .input_r_q0(input_r_q0),
    .input_r_address1(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_address1),
    .input_r_ce1(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_ce1),
    .input_r_q1(input_r_q1),
    .p_cast9_mid2(p_cast9_mid2_reg_724),
    .filters(filters),
    .p_mid216(p_mid216_reg_730),
    .sum_11_out(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_11_out),
    .sum_11_out_ap_vld(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_11_out_ap_vld),
    .sum_23_4_out(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_23_4_out),
    .sum_23_4_out_ap_vld(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_23_4_out_ap_vld),
    .ap_return(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_return),
    .grp_fu_790_p_din0(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_din0),
    .grp_fu_790_p_din1(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_din1),
    .grp_fu_790_p_opcode(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_opcode),
    .grp_fu_790_p_dout0(grp_fu_909_p_dout0),
    .grp_fu_790_p_ce(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_ce),
    .grp_fu_794_p_din0(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_din0),
    .grp_fu_794_p_din1(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_din1),
    .grp_fu_794_p_dout0(grp_fu_913_p_dout0),
    .grp_fu_794_p_ce(grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_ce)
);

lenet_predict_mul_5ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_5ns_8ns_11_1_1_U64(
    .din0(empty_fu_234_p0),
    .din1(empty_fu_234_p1),
    .dout(empty_fu_234_p2)
);

lenet_predict_mul_5ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_5ns_6ns_9_1_1_U65(
    .din0(p_cast9_mid2_fu_338_p0),
    .din1(p_cast9_mid2_fu_338_p1),
    .dout(p_cast9_mid2_fu_338_p2)
);

lenet_predict_mul_5ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_5ns_8ns_11_1_1_U66(
    .din0(p_mid113_fu_345_p0),
    .din1(p_mid113_fu_345_p1),
    .dout(p_mid113_fu_345_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_ready == 1'b1)) begin
            grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0))) begin
            grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_ready == 1'b1)) begin
            grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f_fu_110 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0))) begin
        f_fu_110 <= p_cast9_mid2_v_v_fu_326_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_102 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0))) begin
        i_fu_102 <= select_ln33_2_fu_445_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten35_fu_114 <= 10'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0))) begin
        indvar_flatten35_fu_114 <= add_ln32_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_106 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0))) begin
        indvar_flatten_fu_106 <= select_ln33_3_fu_466_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_98 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0))) begin
        j_fu_98 <= add_ln34_fu_454_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln47_1_reg_778 <= add_ln47_1_fu_584_p2;
        targetBlock1_reg_773 <= grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        or_ln34_reg_767[3 : 1] <= or_ln34_fu_513_p2[3 : 1];
        select_ln38_reg_760 <= select_ln38_fu_505_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0))) begin
        p_cast9_mid2_reg_724 <= p_cast9_mid2_fu_338_p2;
        p_mid216_reg_730 <= p_mid216_fu_359_p2;
        select_ln33_1_reg_743 <= select_ln33_1_fu_437_p3;
        select_ln33_2_reg_749 <= select_ln33_2_fu_445_p3;
        select_ln33_reg_736 <= select_ln33_fu_392_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        select_ln38_1_reg_783 <= select_ln38_1_fu_595_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_11_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        sum_11_loc_fu_122 <= grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_11_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_16_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        sum_16_4_loc_fu_126 <= grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_16_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_23_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        sum_23_4_loc_fu_118 <= grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_sum_23_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        sum_loc_fu_130 <= grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_sum_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        targetBlock_reg_755 <= grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_return;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        grp_fu_191_ce = 1'b1;
    end else begin
        grp_fu_191_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_191_p0 = select_ln38_1_fu_595_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_191_p0 = select_ln38_fu_505_p3;
    end else begin
        grp_fu_191_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_790_ce = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_790_ce = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_ce;
    end else begin
        grp_fu_790_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_790_opcode = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_790_opcode = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_opcode;
    end else begin
        grp_fu_790_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_790_p0 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_790_p0 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_din0;
    end else begin
        grp_fu_790_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_790_p1 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_790_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_790_p1 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_790_p_din1;
    end else begin
        grp_fu_790_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_794_ce = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_794_ce = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_ce;
    end else begin
        grp_fu_794_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_794_p0 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_794_p0 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_din0;
    end else begin
        grp_fu_794_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_794_p1 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_grp_fu_794_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_794_p1 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_grp_fu_794_p_din1;
    end else begin
        grp_fu_794_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_address0 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_address0 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_address0;
    end else begin
        input_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_address1 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_address1 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_address1;
    end else begin
        input_r_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_ce0 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_ce0 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_ce0;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_ce1 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_input_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_ce1 = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_input_r_ce1;
    end else begin
        input_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARADDR = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARADDR = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARADDR;
    end else begin
        m_axi_gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARBURST = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARBURST = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARBURST;
    end else begin
        m_axi_gmem_ARBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARCACHE = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARCACHE = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARCACHE;
    end else begin
        m_axi_gmem_ARCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARID = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARID;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARID = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARID;
    end else begin
        m_axi_gmem_ARID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARLEN = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARLEN = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARLEN;
    end else begin
        m_axi_gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARLOCK = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARLOCK = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARLOCK;
    end else begin
        m_axi_gmem_ARLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARPROT = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARPROT = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARPROT;
    end else begin
        m_axi_gmem_ARPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARQOS = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARQOS = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARQOS;
    end else begin
        m_axi_gmem_ARQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARREGION = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARREGION = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARREGION;
    end else begin
        m_axi_gmem_ARREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARSIZE = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARSIZE = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARSIZE;
    end else begin
        m_axi_gmem_ARSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARUSER = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARUSER = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARUSER;
    end else begin
        m_axi_gmem_ARUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_ARVALID = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_ARVALID = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_ARVALID;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_RREADY = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd0)))) begin
        m_axi_gmem_RREADY = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_m_axi_gmem_RREADY;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        output_r_address0 = zext_ln47_1_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        output_r_address0 = zext_ln47_fu_576_p1;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        output_r_d0 = select_ln7_3_fu_644_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        output_r_d0 = select_ln7_fu_563_p3;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln32_fu_276_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_1_fu_316_p2 = (f_fu_110 + 5'd1);

assign add_ln32_fu_282_p2 = (indvar_flatten35_fu_114 + 10'd1);

assign add_ln33_1_fu_460_p2 = (indvar_flatten_fu_106 + 7'd1);

assign add_ln33_fu_386_p2 = (i_mid29_fu_300_p3 + 4'd1);

assign add_ln34_fu_454_p2 = (select_ln33_fu_392_p3 + 4'd2);

assign add_ln47_1_fu_584_p2 = (zext_ln38_fu_581_p1 + select_ln33_1_reg_743);

assign add_ln47_fu_571_p2 = (zext_ln34_fu_519_p1 + select_ln33_1_reg_743);

assign and_ln7_3_fu_638_p2 = (or_ln7_3_fu_632_p2 & grp_fu_423_p_dout0);

assign and_ln7_fu_557_p2 = (or_ln7_fu_551_p2 & grp_fu_423_p_dout0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign bitcast_ln7_3_fu_603_p1 = select_ln38_1_reg_783;

assign bitcast_ln7_fu_522_p1 = select_ln38_reg_760;

assign empty_70_fu_270_p2 = (tmp_fu_264_p2 + p_shl_cast_fu_248_p1);

assign empty_fu_234_p0 = empty_fu_234_p00;

assign empty_fu_234_p00 = f_fu_110;

assign empty_fu_234_p1 = 11'd100;

assign grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start = grp_conv2d_1_Pipeline_VITIS_LOOP_38_44_fu_176_ap_start_reg;

assign grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start = grp_conv2d_1_Pipeline_VITIS_LOOP_38_4_fu_161_ap_start_reg;

assign grp_fu_423_p_ce = grp_fu_191_ce;

assign grp_fu_423_p_din0 = grp_fu_191_p0;

assign grp_fu_423_p_din1 = 32'd0;

assign grp_fu_423_p_opcode = 5'd2;

assign grp_fu_909_p_ce = grp_fu_790_ce;

assign grp_fu_909_p_din0 = grp_fu_790_p0;

assign grp_fu_909_p_din1 = grp_fu_790_p1;

assign grp_fu_909_p_opcode = grp_fu_790_opcode;

assign grp_fu_913_p_ce = grp_fu_794_ce;

assign grp_fu_913_p_din0 = grp_fu_794_p0;

assign grp_fu_913_p_din1 = grp_fu_794_p1;

assign i_mid29_fu_300_p3 = ((icmp_ln33_fu_294_p2[0:0] == 1'b1) ? 4'd0 : i_fu_102);

assign icmp_ln32_fu_276_p2 = ((indvar_flatten35_fu_114 == 10'd800) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_294_p2 = ((indvar_flatten_fu_106 == 7'd50) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_374_p2 = ((j_fu_98 < 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln34_mid234_fu_380_p2 = (icmp_ln34_fu_374_p2 | icmp_ln33_fu_294_p2);

assign icmp_ln7_6_fu_545_p2 = ((trunc_ln7_fu_535_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_7_fu_620_p2 = ((tmp_12_fu_606_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln7_8_fu_626_p2 = ((trunc_ln7_3_fu_616_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_539_p2 = ((tmp_s_fu_525_p4 != 8'd255) ? 1'b1 : 1'b0);

assign j_mid210_fu_308_p3 = ((icmp_ln33_fu_294_p2[0:0] == 1'b1) ? 4'd0 : j_fu_98);

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 32'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign or_ln34_fu_513_p2 = (select_ln33_reg_736 | 4'd1);

assign or_ln7_3_fu_632_p2 = (icmp_ln7_8_fu_626_p2 | icmp_ln7_7_fu_620_p2);

assign or_ln7_fu_551_p2 = (icmp_ln7_fu_539_p2 | icmp_ln7_6_fu_545_p2);

assign p_cast9_mid2_fu_338_p0 = p_cast9_mid2_fu_338_p00;

assign p_cast9_mid2_fu_338_p00 = p_cast9_mid2_v_v_fu_326_p3;

assign p_cast9_mid2_fu_338_p1 = 9'd25;

assign p_cast9_mid2_v_v_fu_326_p3 = ((icmp_ln33_fu_294_p2[0:0] == 1'b1) ? add_ln32_1_fu_316_p2 : f_fu_110);

assign p_mid113_fu_345_p0 = p_mid113_fu_345_p00;

assign p_mid113_fu_345_p00 = add_ln32_1_fu_316_p2;

assign p_mid113_fu_345_p1 = 11'd100;

assign p_mid1_fu_431_p2 = (tmp_mid1_fu_425_p2 + p_shl_cast_mid1_fu_409_p1);

assign p_mid214_fu_351_p3 = ((icmp_ln33_fu_294_p2[0:0] == 1'b1) ? p_mid113_fu_345_p2 : empty_fu_234_p2);

assign p_mid216_fu_359_p2 = (p_cast9_mid2_fu_338_p2 + 9'd5);

assign p_mid232_fu_366_p3 = ((icmp_ln33_fu_294_p2[0:0] == 1'b1) ? p_mid113_fu_345_p2 : empty_70_fu_270_p2);

assign p_shl1_cast_fu_260_p1 = p_shl1_fu_252_p3;

assign p_shl1_cast_mid1_fu_421_p1 = p_shl1_mid1_fu_413_p3;

assign p_shl1_fu_252_p3 = {{i_fu_102}, {1'd0}};

assign p_shl1_mid1_fu_413_p3 = {{add_ln33_fu_386_p2}, {1'd0}};

assign p_shl_cast_fu_248_p1 = p_shl_fu_240_p3;

assign p_shl_cast_mid1_fu_409_p1 = p_shl_mid1_fu_401_p3;

assign p_shl_fu_240_p3 = {{i_fu_102}, {3'd0}};

assign p_shl_mid1_fu_401_p3 = {{add_ln33_fu_386_p2}, {3'd0}};

assign select_ln33_1_fu_437_p3 = ((icmp_ln34_mid234_fu_380_p2[0:0] == 1'b1) ? p_mid232_fu_366_p3 : p_mid1_fu_431_p2);

assign select_ln33_2_fu_445_p3 = ((icmp_ln34_mid234_fu_380_p2[0:0] == 1'b1) ? i_mid29_fu_300_p3 : add_ln33_fu_386_p2);

assign select_ln33_3_fu_466_p3 = ((icmp_ln33_fu_294_p2[0:0] == 1'b1) ? 7'd1 : add_ln33_1_fu_460_p2);

assign select_ln33_fu_392_p3 = ((icmp_ln34_mid234_fu_380_p2[0:0] == 1'b1) ? j_mid210_fu_308_p3 : 4'd0);

assign select_ln38_1_fu_595_p3 = ((targetBlock1_reg_773[0:0] == 1'b1) ? sum_11_loc_fu_122 : sum_23_4_loc_fu_118);

assign select_ln38_fu_505_p3 = ((targetBlock_reg_755[0:0] == 1'b1) ? sum_loc_fu_130 : sum_16_4_loc_fu_126);

assign select_ln7_3_fu_644_p3 = ((and_ln7_3_fu_638_p2[0:0] == 1'b1) ? select_ln38_1_reg_783 : 32'd0);

assign select_ln7_fu_563_p3 = ((and_ln7_fu_557_p2[0:0] == 1'b1) ? select_ln38_reg_760 : 32'd0);

assign tmp_12_fu_606_p4 = {{bitcast_ln7_3_fu_603_p1[30:23]}};

assign tmp_fu_264_p2 = (p_shl1_cast_fu_260_p1 + empty_fu_234_p2);

assign tmp_mid1_fu_425_p2 = (p_shl1_cast_mid1_fu_421_p1 + p_mid214_fu_351_p3);

assign tmp_s_fu_525_p4 = {{bitcast_ln7_fu_522_p1[30:23]}};

assign trunc_ln7_3_fu_616_p1 = bitcast_ln7_3_fu_603_p1[22:0];

assign trunc_ln7_fu_535_p1 = bitcast_ln7_fu_522_p1[22:0];

assign zext_ln34_fu_519_p1 = select_ln33_reg_736;

assign zext_ln38_fu_581_p1 = or_ln34_reg_767;

assign zext_ln47_1_fu_652_p1 = add_ln47_1_reg_778;

assign zext_ln47_fu_576_p1 = add_ln47_fu_571_p2;

always @ (posedge ap_clk) begin
    or_ln34_reg_767[0] <= 1'b1;
end

endmodule //lenet_predict_conv2d_1
