// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lenet_predict_conv2d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        grp_fu_694_p_din0,
        grp_fu_694_p_din1,
        grp_fu_694_p_opcode,
        grp_fu_694_p_dout0,
        grp_fu_694_p_ce,
        grp_fu_308_p_din0,
        grp_fu_308_p_din1,
        grp_fu_308_p_opcode,
        grp_fu_308_p_dout0,
        grp_fu_308_p_ce,
        grp_fu_303_p_din0,
        grp_fu_303_p_din1,
        grp_fu_303_p_opcode,
        grp_fu_303_p_dout0,
        grp_fu_303_p_ce,
        grp_fu_698_p_din0,
        grp_fu_698_p_din1,
        grp_fu_698_p_dout0,
        grp_fu_698_p_ce
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [10:0] input_r_address1;
output   input_r_ce1;
input  [31:0] input_r_q1;
output  [10:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
output  [31:0] grp_fu_694_p_din0;
output  [31:0] grp_fu_694_p_din1;
output  [1:0] grp_fu_694_p_opcode;
input  [31:0] grp_fu_694_p_dout0;
output   grp_fu_694_p_ce;
output  [31:0] grp_fu_308_p_din0;
output  [31:0] grp_fu_308_p_din1;
output  [4:0] grp_fu_308_p_opcode;
input  [0:0] grp_fu_308_p_dout0;
output   grp_fu_308_p_ce;
output  [31:0] grp_fu_303_p_din0;
output  [31:0] grp_fu_303_p_din1;
output  [0:0] grp_fu_303_p_opcode;
input  [31:0] grp_fu_303_p_dout0;
output   grp_fu_303_p_ce;
output  [31:0] grp_fu_698_p_din0;
output  [31:0] grp_fu_698_p_din1;
input  [31:0] grp_fu_698_p_dout0;
output   grp_fu_698_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[10:0] input_r_address0;
reg input_r_ce0;
reg[10:0] input_r_address1;
reg input_r_ce1;
reg[10:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_159;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state9;
wire   [3:0] select_ln31_8_fu_342_p3;
reg   [3:0] select_ln31_8_reg_672;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln30_fu_244_p2;
wire   [10:0] select_ln31_9_fu_387_p3;
reg   [10:0] select_ln31_9_reg_679;
wire   [3:0] select_ln31_10_fu_395_p3;
reg   [3:0] select_ln31_10_reg_685;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_return;
reg   [0:0] targetBlock_reg_691;
wire    ap_CS_fsm_state3;
wire   [31:0] select_ln35_fu_455_p3;
wire    ap_CS_fsm_state4;
wire   [3:0] or_ln32_fu_463_p2;
reg   [3:0] or_ln32_reg_701;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_return;
reg   [0:0] targetBlock2_reg_707;
wire    ap_CS_fsm_state5;
wire   [31:0] select_ln35_2_fu_475_p3;
wire    ap_CS_fsm_state6;
wire   [10:0] add_ln42_2_fu_550_p2;
reg   [10:0] add_ln42_2_reg_717;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_done;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_idle;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_ready;
wire   [10:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_ce0;
wire   [10:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_address1;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_ce1;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_out;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_out_ap_vld;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_22_4_out;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_22_4_out_ap_vld;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_din0;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_din1;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_opcode;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_ce;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_din0;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_din1;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_ce;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_done;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_idle;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_ready;
wire   [10:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_ce0;
wire   [10:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_address1;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_ce1;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_10_out;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_10_out_ap_vld;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_29_4_out;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_29_4_out_ap_vld;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_din0;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_din1;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_opcode;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_ce;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_din0;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_din1;
wire    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_ce;
reg    grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start_reg;
reg   [31:0] sum_loc_fu_104;
reg   [31:0] sum_22_4_loc_fu_100;
reg    grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start_reg;
reg   [31:0] sum_10_loc_fu_96;
reg   [31:0] sum_29_4_loc_fu_92;
wire   [63:0] zext_ln42_fu_542_p1;
wire   [63:0] zext_ln42_2_fu_606_p1;
wire    ap_CS_fsm_state11;
reg   [3:0] j_fu_72;
wire   [3:0] add_ln32_fu_404_p2;
reg   [3:0] i_fu_76;
reg   [6:0] indvar_flatten_fu_80;
wire   [6:0] select_ln31_11_fu_416_p3;
reg   [4:0] f_fu_84;
wire   [4:0] select_ln30_fu_328_p3;
reg   [9:0] indvar_flatten26_fu_88;
wire   [9:0] add_ln30_fu_250_p2;
wire   [31:0] select_ln6_fu_528_p3;
wire   [31:0] select_ln6_2_fu_597_p3;
reg   [31:0] grp_fu_149_p0;
wire    ap_CS_fsm_state8;
wire   [4:0] mul_ln31_fu_202_p0;
wire   [7:0] mul_ln31_fu_202_p1;
wire   [6:0] p_shl_fu_208_p3;
wire   [4:0] p_shl1_fu_220_p3;
wire   [10:0] p_shl1_cast_fu_228_p1;
wire   [10:0] mul_ln31_fu_202_p2;
wire   [10:0] tmp_fu_232_p2;
wire   [10:0] p_shl_cast_fu_216_p1;
wire   [0:0] icmp_ln31_fu_262_p2;
wire   [4:0] add_ln30_2_fu_284_p2;
wire   [4:0] mul_ln31_1_fu_294_p0;
wire   [7:0] mul_ln31_1_fu_294_p1;
wire   [10:0] mul_ln31_1_fu_294_p2;
wire   [10:0] empty_fu_238_p2;
wire   [0:0] icmp_ln32_fu_316_p2;
wire   [3:0] select_ln31_fu_268_p3;
wire   [0:0] or_ln31_fu_322_p2;
wire   [3:0] select_ln31_5_fu_276_p3;
wire   [3:0] add_ln31_fu_336_p2;
wire   [6:0] p_shl_mid1_fu_351_p3;
wire   [4:0] p_shl1_mid1_fu_363_p3;
wire   [10:0] p_shl1_cast_mid1_fu_371_p1;
wire   [10:0] select_ln31_6_fu_300_p3;
wire   [10:0] tmp_mid1_fu_375_p2;
wire   [10:0] p_shl_cast_mid1_fu_359_p1;
wire   [10:0] select_ln31_7_fu_308_p3;
wire   [10:0] p_mid1_fu_381_p2;
wire   [6:0] add_ln31_2_fu_410_p2;
wire   [31:0] bitcast_ln6_fu_486_p1;
wire   [7:0] tmp_s_fu_490_p4;
wire   [22:0] trunc_ln6_fu_500_p1;
wire   [0:0] icmp_ln6_9_fu_510_p2;
wire   [0:0] icmp_ln6_fu_504_p2;
wire   [0:0] or_ln6_fu_516_p2;
wire   [0:0] and_ln6_fu_522_p2;
wire   [10:0] zext_ln32_fu_483_p1;
wire   [10:0] add_ln42_fu_537_p2;
wire   [10:0] zext_ln35_fu_547_p1;
wire   [31:0] bitcast_ln6_4_fu_555_p1;
wire   [7:0] tmp_33_fu_559_p4;
wire   [22:0] trunc_ln6_4_fu_569_p1;
wire   [0:0] icmp_ln6_11_fu_579_p2;
wire   [0:0] icmp_ln6_10_fu_573_p2;
wire   [0:0] or_ln6_4_fu_585_p2;
wire   [0:0] and_ln6_4_fu_591_p2;
reg    grp_fu_149_ce;
reg   [31:0] grp_fu_722_p0;
reg   [31:0] grp_fu_722_p1;
reg   [1:0] grp_fu_722_opcode;
reg    grp_fu_722_ce;
reg   [31:0] grp_fu_726_p0;
reg   [31:0] grp_fu_726_p1;
reg    grp_fu_726_ce;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire   [10:0] mul_ln31_1_fu_294_p00;
wire   [10:0] mul_ln31_fu_202_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start_reg = 1'b0;
#0 grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start_reg = 1'b0;
end

lenet_predict_conv2d_Pipeline_VITIS_LOOP_35_4 grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start),
    .ap_done(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_done),
    .ap_idle(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_idle),
    .ap_ready(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_ready),
    .select_ln31_11(select_ln31_10_reg_685),
    .zext_ln32_1(select_ln31_8_reg_672),
    .input_r_address0(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_address0),
    .input_r_ce0(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_ce0),
    .input_r_q0(input_r_q0),
    .input_r_address1(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_address1),
    .input_r_ce1(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_ce1),
    .input_r_q1(input_r_q1),
    .sum_out(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_out),
    .sum_out_ap_vld(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_out_ap_vld),
    .sum_22_4_out(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_22_4_out),
    .sum_22_4_out_ap_vld(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_22_4_out_ap_vld),
    .ap_return(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_return),
    .grp_fu_722_p_din0(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_din0),
    .grp_fu_722_p_din1(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_din1),
    .grp_fu_722_p_opcode(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_opcode),
    .grp_fu_722_p_dout0(grp_fu_303_p_dout0),
    .grp_fu_722_p_ce(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_ce),
    .grp_fu_726_p_din0(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_din0),
    .grp_fu_726_p_din1(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_din1),
    .grp_fu_726_p_dout0(grp_fu_698_p_dout0),
    .grp_fu_726_p_ce(grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_ce)
);

lenet_predict_conv2d_Pipeline_VITIS_LOOP_35_46 grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start),
    .ap_done(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_done),
    .ap_idle(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_idle),
    .ap_ready(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_ready),
    .select_ln31_11(select_ln31_10_reg_685),
    .zext_ln35_2(or_ln32_reg_701),
    .input_r_address0(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_address0),
    .input_r_ce0(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_ce0),
    .input_r_q0(input_r_q0),
    .input_r_address1(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_address1),
    .input_r_ce1(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_ce1),
    .input_r_q1(input_r_q1),
    .sum_10_out(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_10_out),
    .sum_10_out_ap_vld(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_10_out_ap_vld),
    .sum_29_4_out(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_29_4_out),
    .sum_29_4_out_ap_vld(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_29_4_out_ap_vld),
    .ap_return(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_return),
    .grp_fu_722_p_din0(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_din0),
    .grp_fu_722_p_din1(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_din1),
    .grp_fu_722_p_opcode(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_opcode),
    .grp_fu_722_p_dout0(grp_fu_303_p_dout0),
    .grp_fu_722_p_ce(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_ce),
    .grp_fu_726_p_din0(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_din0),
    .grp_fu_726_p_din1(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_din1),
    .grp_fu_726_p_dout0(grp_fu_698_p_dout0),
    .grp_fu_726_p_ce(grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_ce)
);

lenet_predict_mul_5ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_5ns_8ns_11_1_1_U52(
    .din0(mul_ln31_fu_202_p0),
    .din1(mul_ln31_fu_202_p1),
    .dout(mul_ln31_fu_202_p2)
);

lenet_predict_mul_5ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_5ns_8ns_11_1_1_U53(
    .din0(mul_ln31_1_fu_294_p0),
    .din1(mul_ln31_1_fu_294_p1),
    .dout(mul_ln31_1_fu_294_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_ready == 1'b1)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln30_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_ready == 1'b1)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f_fu_84 <= 5'd0;
    end else if (((icmp_ln30_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        f_fu_84 <= select_ln30_fu_328_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_76 <= 4'd0;
    end else if (((icmp_ln30_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_76 <= select_ln31_10_fu_395_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten26_fu_88 <= 10'd0;
    end else if (((icmp_ln30_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten26_fu_88 <= add_ln30_fu_250_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_80 <= 7'd0;
    end else if (((icmp_ln30_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_80 <= select_ln31_11_fu_416_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_72 <= 4'd0;
    end else if (((icmp_ln30_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_fu_72 <= add_ln32_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln42_2_reg_717 <= add_ln42_2_fu_550_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        or_ln32_reg_701[3 : 1] <= or_ln32_fu_463_p2[3 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7))) begin
        reg_159 <= grp_fu_694_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln30_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        select_ln31_10_reg_685 <= select_ln31_10_fu_395_p3;
        select_ln31_8_reg_672 <= select_ln31_8_fu_342_p3;
        select_ln31_9_reg_679 <= select_ln31_9_fu_387_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_10_out_ap_vld == 1'b1))) begin
        sum_10_loc_fu_96 <= grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_10_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_22_4_out_ap_vld == 1'b1))) begin
        sum_22_4_loc_fu_100 <= grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_22_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_29_4_out_ap_vld == 1'b1))) begin
        sum_29_4_loc_fu_92 <= grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_sum_29_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_out_ap_vld == 1'b1))) begin
        sum_loc_fu_104 <= grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_sum_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        targetBlock2_reg_707 <= grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        targetBlock_reg_691 <= grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln30_fu_244_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_fu_244_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state5) & (grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_done == 1'b1)))) begin
        grp_fu_149_ce = 1'b1;
    end else begin
        grp_fu_149_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_149_p0 = select_ln35_2_fu_475_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_149_p0 = select_ln35_fu_455_p3;
    end else begin
        grp_fu_149_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_722_ce = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_722_ce = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_ce;
    end else begin
        grp_fu_722_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_722_opcode = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_722_opcode = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_opcode;
    end else begin
        grp_fu_722_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_722_p0 = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_722_p0 = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_din0;
    end else begin
        grp_fu_722_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_722_p1 = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_722_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_722_p1 = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_722_p_din1;
    end else begin
        grp_fu_722_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_726_ce = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_726_ce = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_ce;
    end else begin
        grp_fu_726_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_726_p0 = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_726_p0 = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_din0;
    end else begin
        grp_fu_726_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_726_p1 = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_grp_fu_726_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_726_p1 = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_grp_fu_726_p_din1;
    end else begin
        grp_fu_726_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_address0 = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_address0 = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_address0;
    end else begin
        input_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_address1 = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_address1 = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_address1;
    end else begin
        input_r_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_ce0;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_ce1 = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_input_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_ce1 = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_input_r_ce1;
    end else begin
        input_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        output_r_address0 = zext_ln42_2_fu_606_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_r_address0 = zext_ln42_fu_542_p1;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state11))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        output_r_d0 = select_ln6_2_fu_597_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_r_d0 = select_ln6_fu_528_p3;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state11))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln30_fu_244_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln30_2_fu_284_p2 = (f_fu_84 + 5'd1);

assign add_ln30_fu_250_p2 = (indvar_flatten26_fu_88 + 10'd1);

assign add_ln31_2_fu_410_p2 = (indvar_flatten_fu_80 + 7'd1);

assign add_ln31_fu_336_p2 = (select_ln31_fu_268_p3 + 4'd1);

assign add_ln32_fu_404_p2 = (select_ln31_8_fu_342_p3 + 4'd2);

assign add_ln42_2_fu_550_p2 = (zext_ln35_fu_547_p1 + select_ln31_9_reg_679);

assign add_ln42_fu_537_p2 = (zext_ln32_fu_483_p1 + select_ln31_9_reg_679);

assign and_ln6_4_fu_591_p2 = (or_ln6_4_fu_585_p2 & grp_fu_308_p_dout0);

assign and_ln6_fu_522_p2 = (or_ln6_fu_516_p2 & grp_fu_308_p_dout0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln6_4_fu_555_p1 = reg_159;

assign bitcast_ln6_fu_486_p1 = reg_159;

assign empty_fu_238_p2 = (tmp_fu_232_p2 + p_shl_cast_fu_216_p1);

assign grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start = grp_conv2d_Pipeline_VITIS_LOOP_35_46_fu_139_ap_start_reg;

assign grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start = grp_conv2d_Pipeline_VITIS_LOOP_35_4_fu_129_ap_start_reg;

assign grp_fu_303_p_ce = grp_fu_722_ce;

assign grp_fu_303_p_din0 = grp_fu_722_p0;

assign grp_fu_303_p_din1 = grp_fu_722_p1;

assign grp_fu_303_p_opcode = grp_fu_722_opcode;

assign grp_fu_308_p_ce = 1'b1;

assign grp_fu_308_p_din0 = reg_159;

assign grp_fu_308_p_din1 = 32'd0;

assign grp_fu_308_p_opcode = 5'd2;

assign grp_fu_694_p_ce = grp_fu_149_ce;

assign grp_fu_694_p_din0 = grp_fu_149_p0;

assign grp_fu_694_p_din1 = 32'd0;

assign grp_fu_694_p_opcode = 2'd0;

assign grp_fu_698_p_ce = grp_fu_726_ce;

assign grp_fu_698_p_din0 = grp_fu_726_p0;

assign grp_fu_698_p_din1 = grp_fu_726_p1;

assign icmp_ln30_fu_244_p2 = ((indvar_flatten26_fu_88 == 10'd800) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_262_p2 = ((indvar_flatten_fu_80 == 7'd50) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_316_p2 = ((j_fu_72 < 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln6_10_fu_573_p2 = ((tmp_33_fu_559_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln6_11_fu_579_p2 = ((trunc_ln6_4_fu_569_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln6_9_fu_510_p2 = ((trunc_ln6_fu_500_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_504_p2 = ((tmp_s_fu_490_p4 != 8'd255) ? 1'b1 : 1'b0);

assign mul_ln31_1_fu_294_p0 = mul_ln31_1_fu_294_p00;

assign mul_ln31_1_fu_294_p00 = add_ln30_2_fu_284_p2;

assign mul_ln31_1_fu_294_p1 = 11'd100;

assign mul_ln31_fu_202_p0 = mul_ln31_fu_202_p00;

assign mul_ln31_fu_202_p00 = f_fu_84;

assign mul_ln31_fu_202_p1 = 11'd100;

assign or_ln31_fu_322_p2 = (icmp_ln32_fu_316_p2 | icmp_ln31_fu_262_p2);

assign or_ln32_fu_463_p2 = (select_ln31_8_reg_672 | 4'd1);

assign or_ln6_4_fu_585_p2 = (icmp_ln6_11_fu_579_p2 | icmp_ln6_10_fu_573_p2);

assign or_ln6_fu_516_p2 = (icmp_ln6_fu_504_p2 | icmp_ln6_9_fu_510_p2);

assign p_mid1_fu_381_p2 = (tmp_mid1_fu_375_p2 + p_shl_cast_mid1_fu_359_p1);

assign p_shl1_cast_fu_228_p1 = p_shl1_fu_220_p3;

assign p_shl1_cast_mid1_fu_371_p1 = p_shl1_mid1_fu_363_p3;

assign p_shl1_fu_220_p3 = {{i_fu_76}, {1'd0}};

assign p_shl1_mid1_fu_363_p3 = {{add_ln31_fu_336_p2}, {1'd0}};

assign p_shl_cast_fu_216_p1 = p_shl_fu_208_p3;

assign p_shl_cast_mid1_fu_359_p1 = p_shl_mid1_fu_351_p3;

assign p_shl_fu_208_p3 = {{i_fu_76}, {3'd0}};

assign p_shl_mid1_fu_351_p3 = {{add_ln31_fu_336_p2}, {3'd0}};

assign select_ln30_fu_328_p3 = ((icmp_ln31_fu_262_p2[0:0] == 1'b1) ? add_ln30_2_fu_284_p2 : f_fu_84);

assign select_ln31_10_fu_395_p3 = ((or_ln31_fu_322_p2[0:0] == 1'b1) ? select_ln31_fu_268_p3 : add_ln31_fu_336_p2);

assign select_ln31_11_fu_416_p3 = ((icmp_ln31_fu_262_p2[0:0] == 1'b1) ? 7'd1 : add_ln31_2_fu_410_p2);

assign select_ln31_5_fu_276_p3 = ((icmp_ln31_fu_262_p2[0:0] == 1'b1) ? 4'd0 : j_fu_72);

assign select_ln31_6_fu_300_p3 = ((icmp_ln31_fu_262_p2[0:0] == 1'b1) ? mul_ln31_1_fu_294_p2 : mul_ln31_fu_202_p2);

assign select_ln31_7_fu_308_p3 = ((icmp_ln31_fu_262_p2[0:0] == 1'b1) ? mul_ln31_1_fu_294_p2 : empty_fu_238_p2);

assign select_ln31_8_fu_342_p3 = ((or_ln31_fu_322_p2[0:0] == 1'b1) ? select_ln31_5_fu_276_p3 : 4'd0);

assign select_ln31_9_fu_387_p3 = ((or_ln31_fu_322_p2[0:0] == 1'b1) ? select_ln31_7_fu_308_p3 : p_mid1_fu_381_p2);

assign select_ln31_fu_268_p3 = ((icmp_ln31_fu_262_p2[0:0] == 1'b1) ? 4'd0 : i_fu_76);

assign select_ln35_2_fu_475_p3 = ((targetBlock2_reg_707[0:0] == 1'b1) ? sum_10_loc_fu_96 : sum_29_4_loc_fu_92);

assign select_ln35_fu_455_p3 = ((targetBlock_reg_691[0:0] == 1'b1) ? sum_loc_fu_104 : sum_22_4_loc_fu_100);

assign select_ln6_2_fu_597_p3 = ((and_ln6_4_fu_591_p2[0:0] == 1'b1) ? reg_159 : 32'd0);

assign select_ln6_fu_528_p3 = ((and_ln6_fu_522_p2[0:0] == 1'b1) ? reg_159 : 32'd0);

assign tmp_33_fu_559_p4 = {{bitcast_ln6_4_fu_555_p1[30:23]}};

assign tmp_fu_232_p2 = (p_shl1_cast_fu_228_p1 + mul_ln31_fu_202_p2);

assign tmp_mid1_fu_375_p2 = (p_shl1_cast_mid1_fu_371_p1 + select_ln31_6_fu_300_p3);

assign tmp_s_fu_490_p4 = {{bitcast_ln6_fu_486_p1[30:23]}};

assign trunc_ln6_4_fu_569_p1 = bitcast_ln6_4_fu_555_p1[22:0];

assign trunc_ln6_fu_500_p1 = bitcast_ln6_fu_486_p1[22:0];

assign zext_ln32_fu_483_p1 = select_ln31_8_reg_672;

assign zext_ln35_fu_547_p1 = or_ln32_reg_701;

assign zext_ln42_2_fu_606_p1 = add_ln42_2_reg_717;

assign zext_ln42_fu_542_p1 = add_ln42_fu_537_p2;

always @ (posedge ap_clk) begin
    or_ln32_reg_701[0] <= 1'b1;
end

endmodule //lenet_predict_conv2d
