@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Sep 30 19:51:01 -0700 2024
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_MAC_unpipelined_top_behav -key {Behavioral:sim_1:Functional:tb_MAC_unpipelined_top} -tclbatch tb_MAC_unpipelined_top.tcl -view C:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/EE278_HW3/tb_MAC_unpipelined_top_behav.wcfg -log simulate.log"
call xsim  tb_MAC_unpipelined_top_behav -key {Behavioral:sim_1:Functional:tb_MAC_unpipelined_top} -tclbatch tb_MAC_unpipelined_top.tcl -view C:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/EE278_HW3/tb_MAC_unpipelined_top_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
