# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/pixel_control/pixel_control.srcs/sources_1/ip/array_add_0_2/array_add_0.xci
# IP: The module: 'array_add_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/pixel_control/pixel_control.gen/sources_1/ip/array_add_0_2/constraints/array_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'array_add_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/pixel_control/pixel_control.srcs/sources_1/ip/array_add_0_2/array_add_0.xci
# IP: The module: 'array_add_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Baron/Desktop/EE_278_Repo/EE_278/vivado_projects/pixel_control/pixel_control.gen/sources_1/ip/array_add_0_2/constraints/array_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'array_add_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
