// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lenet_predict_lenet_predict_Pipeline_VITIS_LOOP_13_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        max_4,
        fc3_output_address0,
        fc3_output_ce0,
        fc3_output_q0,
        max_5_out,
        max_5_out_ap_vld,
        grp_fu_423_p_din0,
        grp_fu_423_p_din1,
        grp_fu_423_p_opcode,
        grp_fu_423_p_dout0,
        grp_fu_423_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] max_4;
output  [3:0] fc3_output_address0;
output   fc3_output_ce0;
input  [31:0] fc3_output_q0;
output  [31:0] max_5_out;
output   max_5_out_ap_vld;
output  [31:0] grp_fu_423_p_din0;
output  [31:0] grp_fu_423_p_din1;
output  [4:0] grp_fu_423_p_opcode;
input  [0:0] grp_fu_423_p_dout0;
output   grp_fu_423_p_ce;

reg ap_idle;
reg fc3_output_ce0;
reg max_5_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln13_fu_96_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln13_reg_234;
reg   [31:0] max_load_1_reg_243;
reg   [31:0] max_3_reg_250;
wire   [63:0] i_5_cast_fu_102_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] max_fu_44;
wire   [31:0] max_5_fu_204_p3;
reg   [31:0] ap_sig_allocacmp_max_load_1;
wire    ap_loop_init;
reg   [3:0] i_fu_48;
wire   [3:0] add_ln13_fu_107_p2;
reg   [3:0] ap_sig_allocacmp_i_5;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] bitcast_ln14_fu_122_p1;
wire   [31:0] bitcast_ln14_1_fu_139_p1;
wire   [7:0] tmp_9_fu_125_p4;
wire   [22:0] trunc_ln14_fu_135_p1;
wire   [0:0] icmp_ln14_1_fu_162_p2;
wire   [0:0] icmp_ln14_fu_156_p2;
wire   [7:0] tmp_s_fu_142_p4;
wire   [22:0] trunc_ln14_1_fu_152_p1;
wire   [0:0] icmp_ln14_3_fu_180_p2;
wire   [0:0] icmp_ln14_2_fu_174_p2;
wire   [0:0] or_ln14_fu_168_p2;
wire   [0:0] and_ln14_fu_192_p2;
wire   [0:0] or_ln14_1_fu_186_p2;
wire   [0:0] and_ln14_1_fu_198_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_predict_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln13_fu_96_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_48 <= add_ln13_fu_107_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 4'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            max_fu_44 <= max_4;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            max_fu_44 <= max_5_fu_204_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln13_reg_234 <= icmp_ln13_fu_96_p2;
        max_3_reg_250 <= fc3_output_q0;
        max_load_1_reg_243 <= ap_sig_allocacmp_max_load_1;
    end
end

always @ (*) begin
    if (((icmp_ln13_fu_96_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_5 = 4'd1;
    end else begin
        ap_sig_allocacmp_i_5 = i_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_max_load_1 = max_5_fu_204_p3;
    end else begin
        ap_sig_allocacmp_max_load_1 = max_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc3_output_ce0 = 1'b1;
    end else begin
        fc3_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_234 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_5_out_ap_vld = 1'b1;
    end else begin
        max_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_fu_107_p2 = (ap_sig_allocacmp_i_5 + 4'd1);

assign and_ln14_1_fu_198_p2 = (or_ln14_1_fu_186_p2 & and_ln14_fu_192_p2);

assign and_ln14_fu_192_p2 = (or_ln14_fu_168_p2 & grp_fu_423_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln14_1_fu_139_p1 = max_load_1_reg_243;

assign bitcast_ln14_fu_122_p1 = max_3_reg_250;

assign fc3_output_address0 = i_5_cast_fu_102_p1;

assign grp_fu_423_p_ce = 1'b1;

assign grp_fu_423_p_din0 = fc3_output_q0;

assign grp_fu_423_p_din1 = ap_sig_allocacmp_max_load_1;

assign grp_fu_423_p_opcode = 5'd2;

assign i_5_cast_fu_102_p1 = ap_sig_allocacmp_i_5;

assign icmp_ln13_fu_96_p2 = ((ap_sig_allocacmp_i_5 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln14_1_fu_162_p2 = ((trunc_ln14_fu_135_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_2_fu_174_p2 = ((tmp_s_fu_142_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_3_fu_180_p2 = ((trunc_ln14_1_fu_152_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_156_p2 = ((tmp_9_fu_125_p4 != 8'd255) ? 1'b1 : 1'b0);

assign max_5_fu_204_p3 = ((and_ln14_1_fu_198_p2[0:0] == 1'b1) ? max_3_reg_250 : max_load_1_reg_243);

assign max_5_out = max_fu_44;

assign or_ln14_1_fu_186_p2 = (icmp_ln14_3_fu_180_p2 | icmp_ln14_2_fu_174_p2);

assign or_ln14_fu_168_p2 = (icmp_ln14_fu_156_p2 | icmp_ln14_1_fu_162_p2);

assign tmp_9_fu_125_p4 = {{bitcast_ln14_fu_122_p1[30:23]}};

assign tmp_s_fu_142_p4 = {{bitcast_ln14_1_fu_139_p1[30:23]}};

assign trunc_ln14_1_fu_152_p1 = bitcast_ln14_1_fu_139_p1[22:0];

assign trunc_ln14_fu_135_p1 = bitcast_ln14_fu_122_p1[22:0];

endmodule //lenet_predict_lenet_predict_Pipeline_VITIS_LOOP_13_1
